&lt;template&gt;
  &lt;div class="min-h-screen bg-gradient-to-br from-cyan-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900"&gt;
    &lt;!-- Hero Section --&gt;
    &lt;section class="relative py-20 overflow-hidden"&gt;
      &lt;div class="absolute inset-0 bg-gradient-to-br from-cyan-600/10 to-purple-600/10"&gt;&lt;/div&gt;
      &lt;div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"&gt;
        &lt;h1 class="text-4xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6"&gt;
          Our &lt;span class="text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 to-purple-600"&gt;Programs&lt;/span&gt;
        &lt;/h1&gt;
        &lt;p class="text-xl md:text-2xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto"&gt;
          Comprehensive initiatives designed to create lasting impact in communities worldwide
        &lt;/p&gt;
      &lt;/div&gt;
    &lt;/section&gt;

    &lt;!-- Programs Grid --&gt;
    &lt;section class="py-20"&gt;
      &lt;div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"&gt;
        &lt;div class="grid gap-12"&gt;
          &lt;!-- Digital Literacy Program --&gt;
          &lt;div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"&gt;
            &lt;div class="order-2 lg:order-1"&gt;
              &lt;div class="bg-gradient-to-br from-cyan-100 to-purple-100 dark:from-cyan-900/20 dark:to-purple-900/20 rounded-2xl p-12 shadow-lg"&gt;
                &lt;div class="text-6xl mb-6 text-center"&gt;📚&lt;/div&gt;
                &lt;h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-6"&gt;Digital Literacy Program&lt;/h2&gt;
                &lt;p class="text-gray-600 dark:text-gray-300 text-lg mb-6"&gt;
                  Our flagship program provides comprehensive computer and internet skills training to people of all ages and backgrounds.
                &lt;/p&gt;
                &lt;div class="space-y-4"&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-cyan-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Basic computer operation and safety&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-purple-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Internet navigation and online safety&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-cyan-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Digital communication tools&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-purple-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Online job applications and e-commerce&lt;/span&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class="order-1 lg:order-2"&gt;
              &lt;div class="bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-lg"&gt;
                &lt;h3 class="text-2xl font-bold text-gray-900 dark:text-white mb-6"&gt;Program Impact&lt;/h3&gt;
                &lt;div class="grid grid-cols-2 gap-6"&gt;
                  &lt;div class="text-center"&gt;
                    &lt;div class="text-3xl font-bold text-cyan-600 dark:text-cyan-400"&gt;5,000+&lt;/div&gt;
                    &lt;div class="text-gray-600 dark:text-gray-300"&gt;Students Trained&lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="text-center"&gt;
                    &lt;div class="text-3xl font-bold text-purple-600 dark:text-purple-400"&gt;92%&lt;/div&gt;
                    &lt;div class="text-gray-600 dark:text-gray-300"&gt;Completion Rate&lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="text-center"&gt;
                    &lt;div class="text-3xl font-bold text-cyan-600 dark:text-cyan-400"&gt;15&lt;/div&gt;
                    &lt;div class="text-gray-600 dark:text-gray-300"&gt;Learning Centers&lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="text-center"&gt;
                    &lt;div class="text-3xl font-bold text-purple-600 dark:text-purple-400"&gt;78%&lt;/div&gt;
                    &lt;div class="text-gray-600 dark:text-gray-300"&gt;Employment Rate&lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;

          &lt;!-- Community Development Initiative --&gt;
          &lt;div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"&gt;
            &lt;div&gt;
              &lt;div class="bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-lg"&gt;
                &lt;h3 class="text-2xl font-bold text-gray-900 dark:text-white mb-6"&gt;Active Projects&lt;/h3&gt;
                &lt;div class="space-y-4"&gt;
                  &lt;div class="border-l-4 border-cyan-600 pl-4"&gt;
                    &lt;h4 class="font-semibold text-gray-900 dark:text-white"&gt;Rural Connectivity Project&lt;/h4&gt;
                    &lt;p class="text-gray-600 dark:text-gray-300"&gt;Bringing internet access to remote villages&lt;/p&gt;
                  &lt;/div&gt;
                  &lt;div class="border-l-4 border-purple-600 pl-4"&gt;
                    &lt;h4 class="font-semibold text-gray-900 dark:text-white"&gt;Smart Agriculture Initiative&lt;/h4&gt;
                    &lt;p class="text-gray-600 dark:text-gray-300"&gt;IoT solutions for sustainable farming&lt;/p&gt;
                  &lt;/div&gt;
                  &lt;div class="border-l-4 border-cyan-600 pl-4"&gt;
                    &lt;h4 class="font-semibold text-gray-900 dark:text-white"&gt;Digital Health Records&lt;/h4&gt;
                    &lt;p class="text-gray-600 dark:text-gray-300"&gt;Modernizing healthcare infrastructure&lt;/p&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div&gt;
              &lt;div class="bg-gradient-to-br from-purple-100 to-cyan-100 dark:from-purple-900/20 dark:to-cyan-900/20 rounded-2xl p-12 shadow-lg"&gt;
                &lt;div class="text-6xl mb-6 text-center"&gt;🌍&lt;/div&gt;
                &lt;h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-6"&gt;Community Development&lt;/h2&gt;
                &lt;p class="text-gray-600 dark:text-gray-300 text-lg mb-6"&gt;
                  Working directly with communities to identify challenges and co-create technology solutions that address local needs.
                &lt;/p&gt;
                &lt;div class="space-y-4"&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-purple-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Community needs assessment&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-cyan-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Technology solution development&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-purple-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Local capacity building&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-cyan-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Sustainable implementation&lt;/span&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;

          &lt;!-- Youth Coding Bootcamp --&gt;
          &lt;div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"&gt;
            &lt;div class="order-2 lg:order-1"&gt;
              &lt;div class="bg-gradient-to-br from-cyan-100 to-purple-100 dark:from-cyan-900/20 dark:to-purple-900/20 rounded-2xl p-12 shadow-lg"&gt;
                &lt;div class="text-6xl mb-6 text-center"&gt;💻&lt;/div&gt;
                &lt;h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-6"&gt;Youth Coding Bootcamp&lt;/h2&gt;
                &lt;p class="text-gray-600 dark:text-gray-300 text-lg mb-6"&gt;
                  Intensive programming courses designed to give young people the skills they need for careers in technology.
                &lt;/p&gt;
                &lt;div class="space-y-4"&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-cyan-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Web development fundamentals&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-purple-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Mobile app development&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-cyan-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Portfolio development&lt;/span&gt;
                  &lt;/div&gt;
                  &lt;div class="flex items-center space-x-3"&gt;
                    &lt;div class="w-2 h-2 bg-purple-600 rounded-full"&gt;&lt;/div&gt;
                    &lt;span class="text-gray-700 dark:text-gray-300"&gt;Career placement assistance&lt;/span&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class="order-1 lg:order-2"&gt;
              &lt;div class="bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-lg"&gt;
                &lt;h3 class="text-2xl font-bold text-gray-900 dark:text-white mb-6"&gt;Success Metrics&lt;/h3&gt;
                &lt;div class="space-y-6"&gt;
                  &lt;div&gt;
                    &lt;div class="flex justify-between mb-2"&gt;
                      &lt;span class="text-gray-600 dark:text-gray-300"&gt;Job Placement Rate&lt;/span&gt;
                      &lt;span class="font-semibold text-cyan-600 dark:text-cyan-400"&gt;85%&lt;/span&gt;
                    &lt;/div&gt;
                    &lt;div class="w-full bg-gray-200 rounded-full h-3"&gt;
                      &lt;div class="bg-gradient-to-r from-cyan-600 to-purple-600 h-3 rounded-full" style="width: 85%"&gt;&lt;/div&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div&gt;
                    &lt;div class="flex justify-between mb-2"&gt;
                      &lt;span class="text-gray-600 dark:text-gray-300"&gt;Course Completion&lt;/span&gt;
                      &lt;span class="font-semibold text-purple-600 dark:text-purple-400"&gt;92%&lt;/span&gt;
                    &lt;/div&gt;
                    &lt;div class="w-full bg-gray-200 rounded-full h-3"&gt;
                      &lt;div class="bg-gradient-to-r from-purple-600 to-cyan-600 h-3 rounded-full" style="width: 92%"&gt;&lt;/div&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div&gt;
                    &lt;div class="flex justify-between mb-2"&gt;
                      &lt;span class="text-gray-600 dark:text-gray-300"&gt;Student Satisfaction&lt;/span&gt;
                      &lt;span class="font-semibold text-cyan-600 dark:text-cyan-400"&gt;96%&lt;/span&gt;
                    &lt;/div&gt;
                    &lt;div class="w-full bg-gray-200 rounded-full h-3"&gt;
                      &lt;div class="bg-gradient-to-r from-cyan-600 to-purple-600 h-3 rounded-full" style="width: 96%"&gt;&lt;/div&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/section&gt;

    &lt;!-- How to Apply Section --&gt;
    &lt;section class="py-20 bg-gradient-to-r from-cyan-600 to-purple-600"&gt;
      &lt;div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"&gt;
        &lt;div class="text-center text-white"&gt;
          &lt;h2 class="text-3xl md:text-4xl font-bold mb-6"&gt;Ready to Join Our Programs?&lt;/h2&gt;
          &lt;p class="text-xl text-cyan-100 mb-8 max-w-3xl mx-auto"&gt;
            Applications are open year-round for all our programs. We believe in making education accessible to everyone.
          &lt;/p&gt;
          &lt;div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12"&gt;
            &lt;div class="bg-white/10 backdrop-blur-sm rounded-2xl p-6"&gt;
              &lt;div class="text-3xl mb-4"&gt;📝&lt;/div&gt;
              &lt;h3 class="text-xl font-semibold mb-2"&gt;1. Apply Online&lt;/h3&gt;
              &lt;p class="text-cyan-100"&gt;Fill out our simple application form with your basic information and program preferences.&lt;/p&gt;
            &lt;/div&gt;
            &lt;div class="bg-white/10 backdrop-blur-sm rounded-2xl p-6"&gt;
              &lt;div class="text-3xl mb-4"&gt;🤝&lt;/div&gt;
              &lt;h3 class="text-xl font-semibold mb-2"&gt;2. Community Matching&lt;/h3&gt;
              &lt;p class="text-cyan-100"&gt;We'll connect you with local coordinators and program schedules in your area.&lt;/p&gt;
            &lt;/div&gt;
            &lt;div class="bg-white/10 backdrop-blur-sm rounded-2xl p-6"&gt;
              &lt;div class="text-3xl mb-4"&gt;🚀&lt;/div&gt;
              &lt;h3 class="text-xl font-semibold mb-2"&gt;3. Start Learning&lt;/h3&gt;
              &lt;p class="text-cyan-100"&gt;Begin your journey with our supportive community and experienced instructors.&lt;/p&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="mt-12"&gt;
            &lt;button class="px-8 py-4 bg-white text-cyan-600 rounded-lg font-semibold hover:bg-gray-100 transition-colors duration-200 mr-4"&gt;
              Apply Now
            &lt;/button&gt;
            &lt;button class="px-8 py-4 border-2 border-white text-white rounded-lg font-semibold hover:bg-white hover:text-cyan-600 transition-colors duration-200"&gt;
              Learn More
            &lt;/button&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/section&gt;
  &lt;/div&gt;
&lt;/template&gt;

&lt;script setup lang="ts"&gt;
import { onMounted } from 'vue'

onMounted(() =&gt; {
  // Initialize any required data or animations
})
&lt;/script&gt;

&lt;style scoped&gt;
/* Additional styles if needed */
&lt;/style&gt;
